version: '3'
services:
  misp:
    image: rbkmoney/misp-core
    build:
        context: core/.
        args:
            - MISP_TAG=${MISP_TAG}
            - PHP_VER=${PHP_VER}

  misp-modules:
    image: rbkmoney/misp-modules
    build:
        context: modules/.
        args:
            - MODULES_TAG=${MODULES_TAG}
