version: '3'
services:

  misp-redis:
    image: redis:5.0.9
    networks:
      ipv6_net:

  misp-db:
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      ipv6_net:

  misp:
    image: rbkmoney/misp-core
    depends_on:
      - misp-redis
      - misp-db
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./server-configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files"
      - "./gnupg:/var/www/MISP/.gnupg"
      - "./ssl/:/etc/nginx/certs"
    environment:
      - "SALT=example"
      - "HOSTNAME=http://localhost:8080"
      #- "CORTEX_URL=https://cortex.host"
      #- "CORTEX_PORT=443"
      #- "CORTEX_KEY=dsadsad"
      - "REDIS_FQDN=misp-redis"
      - "CRON_USER_ID=1"        # The MISP user ID to run cron jobs as
#      - "SYNCSERVERS=1 2 3 4"  # The MISP Feed servers to sync in the cron job
      - "MYSQL_HOST=misp-db"
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example" # NOTE: This should be AlphaNum with no Special Chars. Otherwise, edit config files after first run. 
      - "MYSQL_DATABASE=misp"
      # Optional Settings
      - "NOREDIR=true" # Do not redirect port 80
      - "DISIPV6=false" # Disable IPV6 in nginx
      - "SECURESSL=false" # Enable higher security SSL in nginx
      - "MISP_MODULES_FQDN=http://misp-modules" # Set the MISP Modules FQDN, used for Enrichment_services_url/Import_services_url/Export_services_url
    networks:
      ipv6_net:
  misp-modules:
    image: rbkmoney/misp-modules
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - misp-redis
      - misp-db
    networks:
      ipv6_net:

volumes:
    mysql_data:

networks:
  ipv6_net:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fcc7:b4f4:59f2:9971:22ca::/80"
